// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WinFormsApp4.Models;

public partial class User
{
    public string Passport { get; set; }

    public string FirstName { get; set; }

    public string SurName { get; set; }

    public string LastName { get; set; }

    public string Address { get; set; }

    public string PhoneNumber { get; set; }

    public string Email { get; set; }

    public string IsAdmin { get; set; }

    public int Id { get; set; }

    public int? OrderNumberId { get; set; }

    public string DateBirth { get; set; }

    public string Login { get; set; }

    public string Password { get; set; }
}