// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WinFormsApp4.Models;

public partial class Yahct
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int NumberSeats { get; set; }

    public string Colour { get; set; }

    public string Model { get; set; }

    public string Material { get; set; }

    public string DopEquipment { get; set; }

    public string Machta { get; set; }

    public string StatusWork { get; set; }
}